-- MySQL Script generated by MySQL Workbench
-- Tue 27 Sep 2016 05:44:15 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(50) NOT NULL,
  `last_update` TIMESTAMP NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `country_id_UNIQUE` (`country_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NOT NULL,
  `country_id` INT NOT NULL,
  `last_update` TIMESTAMP NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_id_UNIQUE` (`city_id` ASC),
  INDEX `country_id_idx` (`country_id` ASC),
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(150) NOT NULL,
  `district` VARCHAR(140) NOT NULL,
  `city_id` INT NOT NULL,
  `postal_code` INT NOT NULL,
  `phone` INT NOT NULL,
  `mobile_phone` INT NOT NULL,
  `last_update` TIMESTAMP NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC),
  INDEX `city_id_idx` (`city_id` ASC),
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`service_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service_provider` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service_provider` (
  `service_provider_id` INT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`service_provider_id`),
  UNIQUE INDEX `service_provider_id_UNIQUE` (`service_provider_id` ASC),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(128) NULL,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `primary_phone` INT NOT NULL,
  `secondary_phone` INT NULL,
  `address_id` INT NOT NULL,
  `is_beneficiary` TINYINT(1) NOT NULL,
  `is_service_provider` TINYINT(1) NOT NULL,
  `service_provider_id` INT NULL,
  `user_since` TIMESTAMP NOT NULL,
  `validated_user` TINYINT(1) NOT NULL,
  PRIMARY KEY (`users_id`),
  INDEX `address_id_idx` (`address_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC),
  INDEX `service_provider_id_idx` (`service_provider_id` ASC),
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `service_provider_id`
    FOREIGN KEY (`service_provider_id`)
    REFERENCES `mydb`.`service_provider` (`service_provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`special_needs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`special_needs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`special_needs` (
  `special_needs_id` INT NOT NULL,
  `name` INT NOT NULL,
  `short_description` VARCHAR(200) NULL,
  PRIMARY KEY (`special_needs_id`),
  UNIQUE INDEX `special_needs_id_UNIQUE` (`special_needs_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`special_needs_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`special_needs_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`special_needs_users` (
  `special_needs_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  INDEX `special_needs_id_idx` (`special_needs_id` ASC),
  INDEX `users_id_idx` (`users_id` ASC),
  CONSTRAINT `special_needs_id`
    FOREIGN KEY (`special_needs_id`)
    REFERENCES `mydb`.`special_needs` (`special_needs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_tokens` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_tokens` (
  `users_tokens_id` INT NOT NULL,
  `users_id` INT NULL,
  `token` VARCHAR(200) NULL,
  `valid_until` TIMESTAMP NULL,
  PRIMARY KEY (`users_tokens_id`),
  INDEX `users_id_idx` (`users_id` ASC),
  CONSTRAINT `users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
